### ISSUE TITLE
Is there a particular reason that cards are an abstract class?

### ISSUE THREAD

**Issue by Nbjohnston86** [Xyaneon/Xyaneon.Games.Cards#23]
Hello!

I get that decks are supposed to contain the concept of a card, (like a traditional playing card) but does it need to be an abstract class? The reason I ask this is because it can cause a few issues if someone has already defined their own objects that need to inherit from some other base class (Such as a GameObject), then they can't use this library very easily.

There's two thoughts I have for fixing this (And to keep from breaking changes, even). The first is to add an interface such as `ICard`, and have your abstract class inherit from `ICard`, and change the shuffling algorithm to use `where TCard : ICard`, then a person could add the `ICard` interface to any object they want easily. 

Or Option 2, why specify that it needs to inherit from anything at all? A deck doesn't have to be cards. (Anything could be shuffled, really, like songs). It seems that the underlying data structure it accepts is just IEnumerable, just let people use any objects with this interface?

I appreciate your thoughts on the matter.

**Comment by Xyaneon** [comment]
Hi @Nbjohnston86, thanks for asking! These are good design questions, and I'll post my thoughts on the intended design and your proposed options below.

> The first is to add an interface such as `ICard`, and have your abstract class inherit from `ICard`, and change the shuffling algorithm to use `where TCard : ICard`, then a person could add the `ICard` interface to any object they want easily.

This seems like it could work if you want your card objects to inherit from something other than the provided `Card` class. However, without any methods defined in `ICard`, it would basically be an implementation of a marker interface, which is explicitly [discouraged by Microsoft's .NET design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/interface?redirectedfrom=MSDN) and not considered best practice by others (see [this blog post](https://blog.ndepend.com/marker-interface-isnt-pattern-good-idea/) where the author gives a detailed explanation).

`Card` is an abstract class because it defines an "is-a" relationship between it and its subclasses, while interfaces are better suited for describing a "can-do" relationship. Note that `Card` is an empty class, because cards in general don't do much other than provide information about themselves, which is left up to the subclass to implement.

In C#, decorating classes with custom attributes is the preferred alternative to marker interfaces if this is still the strategy you would want to pursue, but as far as I know it's still not possible to define a generic class where the type must be a class with a specific attribute.

> Or Option 2, why specify that it needs to inherit from anything at all? A deck doesn't have to be cards. (Anything could be shuffled, really, like songs). It seems that the underlying data structure it accepts is just IEnumerable, just let people use any objects with this interface?

This would also work. However, without specifying that `TCard` must be some subclass of `Card`, it means we would now be providing a more general-purpose collection type. There's nothing wrong with that, but it does seem to go beyond the intended scope of what this library is supposed to provide (functionality for decks of cards).

Maybe it might be better if we provide additional public interfaces for custom collections which specify methods for drawing or shuffling contents, and then have `IDrawPile<TCard>` implement those? Or perhaps a `Shuffleable<T>` collection type that it could in turn inherit from. That's something I'll consider for a future version.

Anyways, circling back around to your original use case:

> someone has already defined their own objects that need to inherit from some other base class (Such as a GameObject), then they can't use this library very easily.

...a possible solution I would suggest is to define a new `Card` subclass (perhaps a `GameObjectCard`) which provides your `GameObject` as a property. This would avoid the issue of inheritance by using composition instead. (You mentioned the example of a shuffleable collection of songs above, which I would solve the same way with this library with a new `SongCard` subclass containing the associated song.) Without knowing the broader context of what you need to do with your `GameObject`s, this is just one option off the top of my head. Otherwise, you might be better served with another collection type in the meantime.

Thanks for giving me something to think about! I'll keep this in mind for future development.
